/*注册登录内容*/
export const GET_USER_TYPE = 'GET_USER_TYPE';
export const LOGIN_ERROR_MSG = 'LOGIN_ERROR_MSG';
export const SHORT_MESSAGE_DATA = 'SHORT_MESSAGE_DATA';  
export const SHORT_MESSAGE_STATE = 'SHORT_MESSAGE_STATE';
export const SHORT_MESSAGE_TIME = 'SHORT_MESSAGE_TIME';
export const CHECK_NAME = 'CHECK_NAME';
export const CHECK_ID_CARD = 'CHECK_ID_CARD';
export const CHECK_MAIL = 'CHECK_MAIL';
export const CHECK_PASSWORD = 'CHECK_PASSWORD';
export const CHECK_INSURE_PASSWORD = 'CHECK_INSURE_PASSWORD';
export const CHECK_PHONE_NUMBER = 'CHECK_PHONE_NUMBER';
export const CHECK_IDENTIFY_INFO = 'CHECK_IDENTIFY_INFO';
/*用户信息*/
export const GET_USER_INFO = 'GET_USER_INFO';
/*设置用户模态框*/
export const SET_USER_EDIT_MODAL_STATE = 'SET_USER_EDIT_MODAL_STATE';
/*设置字典表*/
export const GET_DICT_DATA = 'GET_DICT_DATA';
/*设置省份*/
export const SET_PROVINCE_CODE = 'SET_PROVINCE_CODE';
/*检验修改信息*/
export const CHECK_MANAGE_NAME = 'CHECK_MANAGE_NAME';
export const CHECK_MANAGE_ID_CARD = 'CHECK_MANAGE_ID_CARD';
export const CHECK_MANAGE_MAIL = 'CHECK_MANAGE_MAIL';
/*显示保存状态*/
export const SHOW_SAVE_STATE = 'SHOW_SAVE_STATE';
/*显示上次登录信息*/
export const GET_LAST_LOGIN = 'GET_LAST_LOGIN';
/*头像模态框显示隐藏*/
export const SET_HEAD_IMAGE_STATE = 'SET_HEAD_IMAGE_STATE';
/*修改密码状态模态框*/
export const SET_CHANGE_PASSWORD_STATE = 'SET_CHANGE_PASSWORD_STATE';
/*绑定邮箱模态框*/
export const SET_BIND_MAIL_BOX_STATE = 'SET_BIND_MAIL_BOX_STATE';

/*修改电话号模态框状态*/
export const SET_CHANGE_PHONE_NUMBER_STATE = 'SET_CHANGE_PHONE_NUMBER_STATE';
/*确定上传头像*/
export const UPDATE_HEAD_PHOTO = 'UPDATE_HEAD_PHOTO';
/*修改密码模块*/
export const CHECK_CHANGE_OLD_PASSWORD = 'CHECK_CHANGE_OLD_PASSWORD';
export const CHECK_CHANGE_NEW_PASSWORD = 'CHECK_CHANGE_NEW_PASSWORD';
export const CHECK_CHANGE_INSURE_PASSWORD = 'CHECK_CHANGE_INSURE_PASSWORD';
export const SET_PASSWORD_STATE = 'SET_PASSWORD_STATE';
/*修改棒冰手机模块*/
export const CHECK_OLD_PHONE_NUMBER = 'CHECK_OLD_PHONE_NUMBER';
export const CHECK_NEW_PHONE_NUMBER = '';
export const CHECK_IDENTIFY_CODE = 'CHECK_IDENTIFY_CODE';
/*获取历史操作纪录*/
export const GET_OPERATE_HISTORY = 'GET_OPERATE_HISTORY';
/*发送邮件状态*/
export const SEND_MAIL_STATE = 'SEND_MAIL_STATE'
/*首页*/
/*用户课程信息*/
export const GET_USER_COURSE = 'GET_USER_COURSE'
export const GET_USER_COURSE_DETAIL = 'GET_USER_COURSE_DETAIL'
export const SET_COURSE_ID = 'SET_COURSE_ID'
